name: _Gera Keystore (one-shot)
on: { workflow_dispatch: {} }

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Defina aqui os dados do seu certificado (sem acentos).
      - name: Generate upload keystore
        env:
          STORE_PWD: Prodestino@2025
          KEY_PWD:   Prodestino@2025
          KEY_ALIAS: prodestino
          DNAME: "CN=ProDestino, OU=Apps, O=ProDestino, L=Manaus, S=AM, C=BR"
        run: |
          keytool -genkeypair -v \
            -keystore upload.keystore \
            -alias "$KEY_ALIAS" \
            -storepass "$STORE_PWD" \
            -keypass "$KEY_PWD" \
            -keyalg RSA -keysize 2048 -validity 36500 \
            -dname "$DNAME"
          # exporta em base64 para virar Secret depois
          base64 -w0 upload.keystore > keystore.b64
          echo "Keystore gerado."

      - name: Upload artifacts (keystore + base64)
        uses: actions/upload-artifact@v4
        with:
          name: keystore-and-base64
          path: |
            upload.keystore
            keystore.b64
