name: Build Android APK (Debug, no-wrapper)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools and platforms
        run: |
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          yes | sdkmanager --licenses

      # Diagn칩stico r치pido: mostra os arquivos-chave
      - name: Show project files
        run: |
          echo "--- ROOT ---"; ls -la
          echo "--- app ---"; ls -la app || true
          echo "--- settings.gradle ---"; sed -n '1,120p' settings.gradle || true
          echo "--- root build.gradle ---"; sed -n '1,120p' build.gradle || true

      # Usa Gradle 8.9 provisionado pela action (sem wrapper no repo)
      - name: Build Debug APK (Gradle 8.9)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
          # Se o m칩dulo est치 na raiz como :app, mantenha:
          arguments: assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
