name: Build Android APK (Debug, no-wrapper)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools and platforms
        run: |
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          yes | sdkmanager --licenses

      # Usa Gradle 8.9 fornecido pela action (não precisa de gradlew no repo)
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
          # Se o projeto estiver na raiz, deixe "assembleDebug".
          # Se estiver numa pasta, por ex. "android/", troque por "--project-dir android assembleDebug".
          arguments: assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
