name: Build Android APK (Debug)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools and platforms
        run: |
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          yes | sdkmanager --licenses

      # ↓↓↓ Evita action deprecada: baixa Gradle 8.9 e gera o wrapper localmente
      - name: Provision Gradle 8.9 and generate wrapper
        run: |
          set -e
          GRADLE_DIR="$RUNNER_TEMP/gradle-8.9"
          curl -sLo "$RUNNER_TEMP/gradle.zip" https://services.gradle.org/distributions/gradle-8.9-bin.zip
          unzip -q "$RUNNER_TEMP/gradle.zip" -d "$RUNNER_TEMP"
          "$GRADLE_DIR/bin/gradle" --version
          "$GRADLE_DIR/bin/gradle" wrapper --gradle-version 8.9 --distribution-type bin
          chmod +x gradlew

      # Validação oficial do wrapper (segurança)
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      # Configura cache moderno para o Gradle (substitui a action antiga)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Build usando o wrapper (sem warnings deprecatados)
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
